
EXTERNAL_IP=<REDACTED>

DOCKER_USER=<REDACTED>


#each of the values must be diffrent
DOCKER_NETWORK_NAME=<REDACTED>
REMOTE_PROXY_NAME=<REDACTED>
SERVER_PROXY_NAME=<REDACTED>
SERVER_MC_NAME=<REDACTED>

MC_VOLUME=<REDACTED>
MC_WORD_VOLUME=<REDACTED>

MC_VERSION=<REDACTED>

SERVER_MAX_RAM=20460M
SERVER_MIN_RAM=6024M