FROM ubuntu AS build
RUN apt-get update && apt-get install -y unzip wget
# your modpack server files
RUN wget https://mediafilez.forgecdn.net/files/5394/657/TerraFirmaGreg-1.20.x-0.7.12-server.zip
RUN unzip TerraFirmaGreg-1.20.x-0.7.12-server.zip

FROM gcr.io/distroless/java17-debian12 AS run
# copy mods and more
COPY --from=build --chown=root:root /.minecraft /mc
# add custom configs and mods
COPY .minecraft/ /mc/
# load world, if empty it will be generated later
COPY world/ /mc/world/ 

# server files must be a volume, becouse libraries and etc need to update and there is no way to update and stop in build mode
VOLUME [ "/mc" ]
# save world into separate volume to allow for script server update when new version arrive
VOLUME [ "/mc/world" ]

#server
EXPOSE 25565
#rcon
EXPOSE 25575

WORKDIR /mc
ENTRYPOINT ["java","-jar","minecraft_server.jar"]
CMD [ "max_ram","min_ram","nogui" ]